import type { Metadata } from "next";
import ReduxProvider from "utils/ReduxProvider";
import AuthLayout from "views/layout/Auth";
import "./globals.css";

export const metadata: Metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AuthLayout>{children}</AuthLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
